plugins {
    id 'com.android.application' version '9.4.0'
}

android {
    namespace = 'com.github.rsteube.t4'
    compileSdk = 36

    defaultConfig {
        applicationId = 'com.github.rsteube.t4'
        minSdk = 14
        targetSdk = 36
        versionCode = 4
        versionName = '1.4'
    }

    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            proguardFiles(getDefaultProguardFile('proguard-android-optimize.txt'))
        }
    }

    packagingOptions {
        resources {
            excludes += ['/META-INF/*.kotlin_module', '**/kotlin/**']
        }
    }
}

base {
    archivesName = 't4-launcher'
}
