name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install SDK packages
        run: /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0"

      - name: Build
        run: ./gradlew assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: t4-launcher
          path: build/outputs/apk/release/t4-launcher-release-unsigned.apk
